[build]
builder = "NIXPACKS"

[deploy]
startCommand = "cd backend && python server.py"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[env]
PORT = "8001"
PYTHONPATH = "/app/backend"